---
inherits_from: .haml-lint_todo.yml

exclude:
  - 'vendor/**/*'

linters:
  InlineStyles:
    exclude:
      - 'app/views/layouts/mailer.html.haml'
      - 'app/views/employee_mailer/**/*'

  ViewLength:
    exclude:
      - 'app/views/layouts/mailer.html.haml'
      - 'app/views/design_guide/index.html.haml'

  Rubocop:
    enabled: false

...
