#  Copyright (c) 2006-2017, Puzzle ITC GmbH. This file is part of
#  PuzzleTime and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/puzzle/puzzletime.


version: '2'

services:
  ptime:
    image: puzzletime-s2i
    ports:
      - '3000:3000'
    environment:
      - RAILS_ENV=development

  ptimedb:
    image: postgres:9.3
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=puzzletime_development
      - POSTGRES_USER=puzzletime
      - POSTGRES_PASSWORD=timepuzzle

#  ptimecache:
#    image: memcached
#    ports:
#      - '11211:11211'

  ptimemailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1025:1025'
      - '1080:1080'
