#  Copyright (c) 2006-2017, Puzzle ITC GmbH. This file is part of
#  PuzzleTime and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/puzzle/puzzletime.

---
version: '3'

volumes:
  db-data:

services:
  ptimedb:
    image: postgres:16.6
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=puzzletime_development
      - POSTGRES_USER=puzzletime
      - POSTGRES_PASSWORD=timepuzzle

  # ptimecache:
  #   image: memcached
  #   ports:
  #     - '11211:11211'

  ptimemailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1025:1025'
      - '1080:1080'
...
