#  Copyright (c) 2006-2017, Puzzle ITC GmbH. This file is part of
#  PuzzleTime and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/puzzle/puzzletime.


version: '3'

volumes:
  db-data:
  influxdb-data:

services:
  ptimedb:
    image: postgres:9.5
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=puzzletime_development
      - POSTGRES_USER=puzzletime
      - POSTGRES_PASSWORD=timepuzzle

  ptimecache:
    image: memcached
    ports:
      - '11211:11211'

  ptimemailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1025:1025'
      - '1080:1080'

  ptimeinfluxdb:
    image: influxdb:2.0.4
    ports:
      - '8086:8086'
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influxuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=influxpassword
      - DOCKER_INFLUXDB_INIT_ORG=ptime
      - DOCKER_INFLUXDB_INIT_BUCKET=PtimeDefault
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ptimetoken
