---
:output_files:
  - brakeman-output.tabs
:skip_files:
  - app/views/evaluator/_detailrow.html.haml  # Causes brakeman to hang
  - app/views/evaluator/details.html.haml     # Causes brakeman to hang
:skip_checks:
  - CheckModelAttrAccessible
:quiet: true
:report_progress: false
:exit_on_warn: false
