# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 10) do

  create_table "absences", :force => true do |t|
    t.column "name",  :string,                     :null => false
    t.column "payed", :boolean, :default => false
  end

  create_table "clients", :force => true do |t|
    t.column "name",      :string,              :null => false
    t.column "contact",   :string
    t.column "shortname", :string, :limit => 4, :null => false
  end

  create_table "employees", :force => true do |t|
    t.column "firstname",             :string,                                  :null => false
    t.column "lastname",              :string,                                  :null => false
    t.column "shortname",             :string,  :limit => 3,                    :null => false
    t.column "passwd",                :string,                                  :null => false
    t.column "email",                 :string,                                  :null => false
    t.column "management",            :boolean,              :default => false
    t.column "initial_vacation_days", :float
    t.column "ldapname",              :string
  end

  add_index "employees", ["shortname"], :name => "chk_unique_name", :unique => true

  create_table "employments", :force => true do |t|
    t.column "employee_id", :integer
    t.column "percent",     :integer, :null => false
    t.column "start_date",  :date,    :null => false
    t.column "end_date",    :date
  end

  add_index "employments", ["employee_id"], :name => "index_employments_on_employee_id"

  create_table "engine_schema_info", :id => false, :force => true do |t|
    t.column "engine_name", :string
    t.column "version",     :integer
  end

  create_table "holidays", :force => true do |t|
    t.column "holiday_date",  :date,  :null => false
    t.column "musthours_day", :float, :null => false
  end

  create_table "overtime_vacations", :force => true do |t|
    t.column "hours",         :float,   :null => false
    t.column "employee_id",   :integer, :null => false
    t.column "transfer_date", :date,    :null => false
  end

  create_table "projectmemberships", :force => true do |t|
    t.column "project_id",        :integer
    t.column "employee_id",       :integer
    t.column "projectmanagement", :boolean, :default => false
    t.column "last_completed",    :date
  end

  add_index "projectmemberships", ["employee_id"], :name => "index_projectmemberships_on_employee_id"
  add_index "projectmemberships", ["project_id"], :name => "index_projectmemberships_on_project_id"

  create_table "projects", :force => true do |t|
    t.column "client_id",            :integer
    t.column "name",                 :string,                                    :null => false
    t.column "description",          :text
    t.column "billable",             :boolean,              :default => true
    t.column "report_type",          :string,               :default => "month"
    t.column "description_required", :boolean,              :default => false
    t.column "shortname",            :string,  :limit => 3,                      :null => false
  end

  add_index "projects", ["client_id"], :name => "index_projects_on_client_id"
  add_index "projects", ["client_id"], :name => "project_clients"

  create_table "user_notifications", :force => true do |t|
    t.column "date_from", :date, :null => false
    t.column "date_to",   :date
    t.column "message",   :text, :null => false
  end

  create_table "worktimes", :force => true do |t|
    t.column "project_id",      :integer
    t.column "absence_id",      :integer
    t.column "employee_id",     :integer
    t.column "report_type",     :string,                     :null => false
    t.column "work_date",       :date,                       :null => false
    t.column "hours",           :float
    t.column "from_start_time", :time
    t.column "to_end_time",     :time
    t.column "description",     :text
    t.column "billable",        :boolean, :default => true
    t.column "booked",          :boolean, :default => false
    t.column "type",            :string
  end

  add_index "worktimes", ["absence_id", "employee_id", "work_date"], :name => "absence_empl_date_index"
  add_index "worktimes", ["employee_id", "work_date"], :name => "attendance_empl_date_index"
  add_index "worktimes", ["employee_id", "work_date", "absence_id"], :name => "worktimes_absences"
  add_index "worktimes", ["work_date", "employee_id"], :name => "worktimes_attendances"
  add_index "worktimes", ["employee_id", "project_id", "work_date"], :name => "worktimes_projects"

end
