---
name: 'Manual build without tests'

"on":
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build in'
        required: true
        type: choice
        options:
          - pitc-ptime-int
          - pitc-ptime-prod
          - pude-ptime-prod
        default: 'pitc-ptime-int'
      project_name:
        description: 'Project to build for'
        required: true
        type: choice
        options:
          - pitc-ptime-int
          - pitc-ptime-prod
          - pude-ptime-prod
        default: 'pitc-ptime-int'
      push:
        description: 'Should we push the image to the registry?'
        required: true
        type: boolean
        default: true

jobs:
  build-dispatch:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      environment: ${{ inputs.environment }}
      project_name: ${{ inputs.project_name  }}
      push: ${{ inputs.push }}
      registry: registry.puzzle.ch
    secrets:
      PUZZLE_REGISTRY_USERNAME: ${{ secrets.PUZZLE_REGISTRY_USERNAME }}
      PUZZLE_REGISTRY_TOKEN: ${{ secrets.PUZZLE_REGISTRY_TOKEN }}
...
