---
name: "Manual build"

"on":
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to build in"
        required: true
        type: choice
        options:
          - pitc-ptime-int
          - pitc-ptime-prod
          - pude-ptime-int
          - pude-ptime-prod
        default: "pitc-ptime-int"
      project_name:
        description: "Project to build for"
        required: true
        type: choice
        options:
          - pitc-ptime-int
          - pitc-ptime-prod
          - pude-ptime-int
          - pude-ptime-prod
        default: "pitc-ptime-int"
      lint:
        description: "Run lint?"
        required: true
        type: boolean
        default: false
      test:
        description: "Run tests?"
        required: true
        type: boolean
        default: false
      build:
        description: "Build the image?"
        required: true
        type: boolean
        default: true
      push:
        description: "Push the image to the registry?"
        required: true
        type: boolean
        default: true
      sbom:
        description: "Generate and upload the SBOM?"
        required: true
        type: boolean
        default: false

jobs:
  lint:
    if: ${{ inputs.lint }}
    permissions:
      contents: read
      checks: write
      pull-requests: write
    uses: ./.github/workflows/reusable-lint.yaml

  test:
    if: ${{ inputs.test }}
    uses: ./.github/workflows/reusable-test.yaml

  build-dispatch:
    needs: [lint, test]
    if: ${{ inputs.build && !failure() && !cancelled() }}
    uses: ./.github/workflows/reusable-build.yaml
    with:
      environment: ${{ inputs.environment }}
      project_name: ${{ inputs.project_name  }}
      push: ${{ inputs.push }}
    secrets:
      PUZZLE_REGISTRY_USERNAME: ${{ secrets.PUZZLE_REGISTRY_USERNAME }}
      PUZZLE_REGISTRY_TOKEN: ${{ secrets.PUZZLE_REGISTRY_TOKEN }}

  sbom:
    needs: build-dispatch
    if: ${{ inputs.sbom && !failure() && !cancelled() }}
    uses: ./.github/workflows/reusable-sbom.yaml
    with:
      project_name: ${{ inputs.project_name }}
    secrets:
      dependency_track_url: ${{ secrets.DEPTRACK_URL }}
      dependency_track_api_key: ${{ secrets.DEPTRACK_API_KEY }}
...
