name: 'Test'
on:
  push:
    branches:
      - dagger-ci
jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: 'test'
        uses: dagger/dagger-for-github@v7.0.1
        with:
          verb: call
          module: ci
          args: test --dir=./
          version: '0.14.0'
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
