name: 'Code Style Review'
on:
  push:
    branches:
      - dagger-ci
jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: 'lint'
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: ci
          args: lint --dir=./
          version: '0.14.0'
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
