name: 'Code Style Review'
on:
  push:
    branches:
      - dagger-ci
jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'lint'
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          args: lint --directory=./
          # TODO: add the token as github secret
          #cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
